library graphview;

import 'dart:collection';
import 'dart:convert';
import 'dart:math';

import 'package:collection/collection.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

part 'Algorithm.dart';
part 'Graph.dart';
part 'config/NodeDraggingConfiguration.dart';
part 'controller/GraphViewController.dart';
part 'delegate/GraphChildDelegate.dart';
part 'delegate/GraphChildManager.dart';
part 'edgerenderer/ArrowEdgeRenderer.dart';
part 'edgerenderer/EdgeRenderer.dart';
part 'edgerenderer/EdgePathGeometry.dart';
part 'edgerenderer/CurvedEdgeRenderer.dart';
part 'edgerenderer/AnimatedEdgeRenderer.dart';
part 'edgerenderer/AdaptiveEdgeRenderer.dart';
part 'edgerenderer/OrthogonalEdgeRenderer.dart';
part 'edgerenderer/routing/VectorUtils.dart';
part 'edgerenderer/routing/EdgeRoutingConfig.dart';
part 'edgerenderer/routing/EdgeRepulsionSolver.dart';
part 'layered/LayeredAlgorithmBase.dart';
part 'layered/SugiyamaAlgorithm.dart';
part 'layered/SugiyamaAccumulatorTree.dart';
part 'layered/SugiyamaConfiguration.dart';
part 'layered/SugiyamaCoordinateAssignment.dart';
part 'layered/SugiyamaCycleRemoval.dart';
part 'layered/SugiyamaEdgeData.dart';
part 'layered/SugiyamaEdgeRenderer.dart';
part 'layered/GreedyCycleRemoval.dart';
part 'layered/SugiyamaLayerAssignment.dart';
part 'layered/SugiyamaNodeData.dart';
part 'layered/SugiyamaNodeOrdering.dart';
part 'renderobject/GraphViewElement.dart';
part 'renderobject/GraphViewWidget.dart';
part 'renderobject/NodeBoxData.dart';
part 'renderobject/RenderCustomLayoutBox.dart';
part 'util/orientation_utils.dart';
part 'widget/GraphView.dart';

typedef NodeWidgetBuilder = Widget Function(Node node);
typedef EdgeWidgetBuilder = Widget Function(Edge edge);
typedef OnNodeDragStart = void Function(Node node);
typedef OnNodeDragUpdate = void Function(Node node, Offset position);
typedef OnNodeDragEnd = void Function(Node node, Offset finalPosition);
