import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:turing_lab/l10n/app_localizations.dart';
import 'package:turing_lab/l10n/app_localizations_workflows.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  final en = lookupAppLocalizations(const Locale('en'));
  final pt = lookupAppLocalizations(const Locale('pt'));

  test('grammar workflow controls resolve in English and Portuguese', () {
    const cases = {
      'Batch parsing': 'Análise em lote',
      'Grammar batch execution': 'Execução em lote de gramáticas',
      'Automatic (Earley)': 'Automático (Earley)',
      'Brute force': 'Força bruta',
      'Failed to load grammar examples.':
          'Falha ao carregar exemplos de gramática.',
      'Grammar applied to editor.': 'Gramática aplicada ao editor.',
      'Practice Regular Grammar to FA': 'Praticar gramática regular para AF',
      'Unable to preview this transformation.':
          'Não foi possível visualizar esta transformação.',
      'Canonical LR(1) ACTION and GOTO table':
          'Tabela ACTION e GOTO LR(1) canônica',
      'State': 'Estado',
      'No source items': 'Nenhum item de origem',
      'Shift/reduce': 'Deslocamento/redução',
      'Reduce/reduce': 'Redução/redução',
      'Reset execution': 'Reiniciar execução',
      'Previous step': 'Passo anterior',
      'Pause execution': 'Pausar execução',
      'Play execution': 'Reproduzir execução',
      'Next step': 'Próximo passo',
      'Diagnostic': 'Diagnóstico',
      'State stack': 'Pilha de estados',
      'Symbol stack': 'Pilha de símbolos',
      'Lookup': 'Consulta',
      'Reduction': 'Redução',
      'Process Cell': 'Processar célula',
      'Check Split': 'Verificar divisão',
      'Apply Production': 'Aplicar produção',
      'Complete Cell': 'Concluir célula',
      'Completion': 'Conclusão',
      'Check Acceptance': 'Verificar aceitação',
    };

    for (final entry in cases.entries) {
      expect(en.localizeWorkflowText(entry.key), entry.key);
      expect(pt.localizeWorkflowText(entry.key), entry.value);
    }
  });

  test('LR(1) and LL(1) dynamic diagnostics preserve formal notation', () {
    const cases = {
      '2 source item(s)': '2 itens de origem',
      'S · viable prefix: ε': 'S · prefixo viável: ε',
      'ACTION I0, a: empty': 'AÇÃO I0, a: vazio',
      'GOTO I1, S: empty': 'GOTO I1, S: vazio',
      'Shift/reduce at [I2, \$]': 'Deslocamento/redução em [I2, \$]',
      'Actions: s3, rp1\nWitness prefix: id\nSources: S → id ·':
          'Ações: s3, rp1\nPrefixo testemunha: id\nOrigens: S → id ·',
      'Shifted id and entered I3.': 'Deslocou id e entrou em I3.',
      'Reduced by p1: S → id.': 'Reduziu por p1: S → id.',
      'No ACTION for [I0, \$].': 'Nenhuma ação ACTION para [I0, \$].',
      'Conflicting ACTION entries at [I2, +].':
          'Entradas ACTION conflitantes em [I2, +].',
      'Selected S → id from table[S, id].':
          'Selecionado S → id da tabela [S, id].',
      'Grammar is not LL(1): conflict at [S, a]: p1 vs p2.':
          'A gramática não é LL(1): conflito em [S, a]: p1 vs p2.',
      'Step 2 of 4': 'Passo 2 de 4',
    };

    for (final entry in cases.entries) {
      expect(en.localizeWorkflowText(entry.key), entry.key);
      expect(pt.localizeWorkflowText(entry.key), entry.value);
    }
  });

  test('CYK step explanations are translated while symbols stay intact', () {
    const cases = {
      'Match terminal "a"': 'Corresponder terminal "a"',
      'Process substring "ab"': 'Processar subcadeia "ab"',
      'Try split "a" | "b"': 'Tentar divisão "a" | "b"',
      'Process cell [1][0]': 'Processar célula [1][0]',
      'Check split at position 1': 'Verificar divisão na posição 1',
      'Complete cell [1][0]': 'Concluir célula [1][0]',
      'Cell [1][0] complete': 'Célula [1][0] concluída',
      'Start symbol S is present → ACCEPT.':
          'O símbolo inicial S está presente → ACEITA.',
      'Start symbol S is missing → REJECT.':
          'O símbolo inicial S está ausente → REJEITA.',
      'Filled 2 / 3 cells.': 'Preenchidas 2 / 3 células.',
      'Result: ACCEPT (string is generated by the grammar).':
          'Resultado: ACEITA (a cadeia é gerada pela gramática).',
      'Result: REJECT (string is not generated by the grammar).':
          'Resultado: REJEITA (a cadeia não é gerada pela gramática).',
    };

    for (final entry in cases.entries) {
      expect(en.localizeWorkflowText(entry.key), entry.key);
      expect(pt.localizeWorkflowText(entry.key), entry.value);
    }
  });

  test('manual derivation controls keep dynamic labels localized', () {
    const cases = {
      '3 matching occurrence(s)': '3 ocorrência(s) correspondente(s)',
      'Position 2': 'Posição 2',
      'Hint search: 4 expanded, 2 queued':
          'Busca de dica: 4 expandidos, 2 na fila',
      'Search-derived suggestion: apply p1 at position 2.':
          'Sugestão da busca: aplique p1 na posição 2.',
      'Hint search reached the frontier limit. The result is inconclusive.':
          'A busca de dica atingiu o limite fronteira. O resultado é inconclusivo.',
      'The saved derivation session is malformed.':
          'A sessão de derivação salva está malformada.',
    };

    for (final entry in cases.entries) {
      expect(en.localizeWorkflowText(entry.key), entry.key);
      expect(pt.localizeWorkflowText(entry.key), entry.value);
    }
  });

  test('batch progress keeps locale-formatted counts in both languages', () {
    const cases = {
      'Batch progress: 1,234 of 2,345 cases complete':
          'Progresso do lote: 1,234 de 2,345 casos concluídos',
      '1.234 of 2.345 cases complete': '1.234 de 2.345 casos concluídos',
    };

    for (final entry in cases.entries) {
      expect(en.localizeWorkflowText(entry.key), entry.key);
      expect(pt.localizeWorkflowText(entry.key), entry.value);
    }
  });
}
