import 'package:flutter_test/flutter_test.dart';
import 'package:turing_lab/core/algorithms/grammar_analyzer.dart';
import 'package:turing_lab/core/algorithms/grammar_analysis_messages.dart';
import 'package:turing_lab/core/algorithms/tm_building_block_messages.dart';
import 'package:turing_lab/core/messages/structured_message.dart';
import 'package:turing_lab/data/codecs/fsa_jflap_messages.dart';
import 'package:turing_lab/data/codecs/grammar_jflap_messages.dart';
import 'package:turing_lab/data/codecs/l_system_jflap_messages.dart';
import 'package:turing_lab/data/codecs/pda_jflap_messages.dart';
import 'package:turing_lab/data/codecs/pda_json_messages.dart';
import 'package:turing_lab/data/codecs/regex_codec_messages.dart';
import 'package:turing_lab/data/codecs/tm_jflap_messages.dart';
import 'package:turing_lab/data/codecs/tm_json_messages.dart';
import 'package:turing_lab/data/codecs/versioned_json_messages.dart';
import 'package:turing_lab/l10n/app_localizations_en.dart';
import 'package:turing_lab/l10n/app_localizations_pt.dart';
import 'package:turing_lab/l10n/app_localizations_structured_messages.dart';

void main() {
  final en = AppLocalizationsEn();
  final pt = AppLocalizationsPt();

  test('new FSA, grammar, and TM payloads resolve in both locales', () {
    final messages = <StructuredMessage>[
      FsaJflapMessages.invalidRoot(),
      FsaJflapMessages.unsupportedDocumentType('tm'),
      FsaJflapMessages.buildingBlocksUnsupported(),
      FsaJflapMessages.missingAutomaton(),
      FsaJflapMessages.missingStateId(),
      FsaJflapMessages.duplicateStateId('q1'),
      FsaJflapMessages.invalidStateCoordinate('q2'),
      FsaJflapMessages.multipleInitialStates(),
      FsaJflapMessages.invalidDocument(),
      FsaJflapMessages.unsupportedSchema(3),
      FsaJflapMessages.requiresFsaDocument(),
      FsaJflapMessages.canonicalOrderImport(),
      FsaJflapMessages.canonicalOrderExport(),
      FsaJflapMessages.stateTypeDropped('q3'),
      FsaJflapMessages.statePropertiesDropped('q3'),
      FsaJflapMessages.transitionControlPointDropped(
        transitionId: 't1',
        x: 1.5,
        y: -2,
      ),
      FsaJflapMessages.transitionDisplayLabelDropped(
        transitionId: 't1',
        label: 'a',
      ),
      FsaJflapMessages.explicitEpsilonAliasInterpreted('ε'),
      FsaJflapMessages.explicitEpsilonAliasExported(
        transitionId: 't1',
        aliases: 'lambda,eps',
      ),
      FsaJflapMessages.multiSymbolTransitionExpanded(
        transitionId: 't1',
        symbolCount: 2,
      ),
      FsaJflapMessages.unknownOptionalElement('foo'),
      FsaJflapMessages.unknownOptionalAttribute('bar'),
      GrammarAnalysisMessages.emptyProductions(),
      GrammarAnalysisMessages.noLeftRecursion(),
      GrammarAnalysisMessages.firstProductionLhsUndeclared('S'),
      GrammarAnalysisMessages.firstEpsilonFromEmptyProduction('S'),
      GrammarAnalysisMessages.firstEpsilonFromProduction('S', 'S → ε'),
      GrammarAnalysisMessages.firstTerminalFromProduction(
        left: 'S',
        symbol: 'a',
        production: 'S → a',
      ),
      GrammarAnalysisMessages.firstAbsorbsFirst(
        left: 'S',
        source: 'A',
        production: 'S → A',
      ),
      GrammarAnalysisMessages.firstEpsilonFromNullableProduction(
        left: 'S',
        production: 'S → A B',
      ),
      GrammarAnalysisMessages.firstSetsComputed(2),
      GrammarAnalysisMessages.followStartSymbolUndeclared('S'),
      GrammarAnalysisMessages.followStartSymbolMissingEntry('S'),
      GrammarAnalysisMessages.followStartIncludesEndMarker('S'),
      GrammarAnalysisMessages.followProductionLhsUndeclared('S'),
      GrammarAnalysisMessages.followGainsFromSuffix(
        symbol: 'A',
        gained: 'b, c',
        production: 'S → A b',
      ),
      GrammarAnalysisMessages.followAbsorbsFollow(
        symbol: 'A',
        source: 'S',
        production: 'S → A',
      ),
      GrammarAnalysisMessages.followSetsComputed(2),
      GrammarAnalysisMessages.processingOrder('S, A'),
      GrammarAnalysisMessages.substitutionNote(production: 'A → S a', via: 'S'),
      GrammarAnalysisMessages.substitutionDerivation(
        production: 'A → S a',
        replacements: 'A → b a',
      ),
      GrammarAnalysisMessages.substitutionOperation(current: 'A', via: 'S'),
      GrammarAnalysisMessages.substitutionRationale(current: 'A', via: 'S'),
      GrammarAnalysisMessages.removeVacuousRecursionRationale('S'),
      GrammarAnalysisMessages.vacuousRecursionDerivation('S → S'),
      GrammarAnalysisMessages.recursiveOnlyRationale('S'),
      GrammarAnalysisMessages.recursiveOnlyDerivation('S'),
      GrammarAnalysisMessages.directRecursionIntroduced(
        introduced: "S'",
        nonTerminal: 'S',
      ),
      GrammarAnalysisMessages.moveRecursiveSuffixesRationale(
        nonTerminal: 'S',
        introduced: "S'",
      ),
      GrammarAnalysisMessages.directRecursionRewrittenDerivation(
        nonTerminal: 'S',
        introduced: "S'",
      ),
      GrammarAnalysisMessages.directRecursionOperation('S'),
      GrammarAnalysisMessages.leftCornerCycleRemains(),
      GrammarAnalysisMessages.leftRecursionRemoved(),
      GrammarPredictiveMessages.factoringIntroduced(
        nonTerminal: 'S',
        introduced: 'S_1',
        prefix: 'a',
        productionCount: 2,
      ),
      GrammarPredictiveMessages.factoringDerivation(
        nonTerminal: 'S',
        introduced: 'S_1',
        prefix: 'a',
        productionCount: 2,
      ),
      GrammarPredictiveMessages.factoringSuffix(introduced: 'S_1', suffix: 'b'),
      GrammarPredictiveMessages.noFactoringNeeded(),
      GrammarPredictiveMessages.productionLhsUndeclared('S'),
      GrammarPredictiveMessages.missingTableRow('S'),
      GrammarPredictiveMessages.missingFollowOrTableEntry('S'),
      GrammarPredictiveMessages.tablePlacement(
        placement: LL1TablePlacement.first,
        nonTerminal: 'S',
        production: 'S → a',
        lookahead: 'a',
      ),
      GrammarPredictiveMessages.tablePlacement(
        placement: LL1TablePlacement.follow,
        nonTerminal: 'S',
        production: 'S → ε',
        lookahead: '\$',
      ),
      GrammarPredictiveMessages.tableConstructed(2),
      GrammarPredictiveMessages.tableNoConflicts(),
      GrammarPredictiveMessages.tableConflictsDetected(1),
      GrammarJflapMessages.unsupportedDocumentType('fa'),
      GrammarJflapMessages.emptyGrammar(),
      GrammarJflapMessages.missingProductionSide(0),
      GrammarJflapMessages.startSymbolUndetermined(),
      GrammarJflapMessages.unknownGrammarTypePreserved('vendor'),
      GrammarJflapMessages.unknownOptionalElement('extensions'),
      GrammarJflapMessages.tokenizationNormalized(),
      GrammarJflapMessages.requiresGrammarDocument(),
      GrammarJflapMessages.unsupportedSchema(2),
      GrammarJflapMessages.invalidDocument(),
      GrammarJflapMessages.tokenBoundariesLossy('aa'),
      GrammarJflapMessages.classificationLossy('regular'),
      LSystemJflapMessages.invalidRoot(),
      LSystemJflapMessages.unsupportedDocumentType('fa'),
      LSystemJflapMessages.missingAxiom(),
      LSystemJflapMessages.malformedXml(),
      LSystemJflapMessages.invalidUtf8(),
      LSystemJflapMessages.emptyPredecessor(),
      LSystemJflapMessages.invalidContextPredecessor('A < B'),
      LSystemJflapMessages.invalidParameter(name: 'iterations'),
      LSystemJflapMessages.invalidParameter(name: 'iterations', value: '-1'),
      LSystemJflapMessages.invalidExtension('turingLabExtensions'),
      LSystemJflapMessages.invalidProductionMetadata('weight'),
      LSystemJflapMessages.invalidCommandMapping(),
      LSystemJflapMessages.invalidDocument(),
      LSystemJflapMessages.requiresLSystemDocument(),
      LSystemJflapMessages.unsupportedSchema(2),
      LSystemJflapMessages.decodeFailed(),
      LSystemJflapMessages.encodeFailed(),
      LSystemJflapMessages.advancedVariantPreserved(),
      LSystemJflapMessages.parametersPreserved('angle, step'),
      LSystemJflapMessages.executionExtensionRestored(),
      LSystemJflapMessages.elementsPreserved(),
      LSystemJflapMessages.executionExtension(),
      LSystemJflapMessages.advancedVariantExtension(),
      RegexJflapMessages.unsupportedDocument(),
      RegexJflapMessages.multipleExpressions(),
      RegexJflapMessages.multipleExtensions(),
      RegexJflapMessages.invalidExtension(),
      RegexJflapMessages.extensionMismatch(),
      RegexJflapMessages.dialectNormalized(),
      RegexJflapMessages.unsupportedFeature('lookahead'),
      RegexJflapMessages.invalidDocument(),
      RegexJflapMessages.malformedDocument(),
      RegexJflapMessages.expectedRegexDocument(),
      RegexJflapMessages.portabilityLossy(),
      RegexJflapMessages.emptySetInteroperability(),
      RegexJflapMessages.unbalancedParentheses(),
      RegexJflapMessages.malformedOperators(),
      RegexJflapMessages.unionMissingOperand(),
      RegexJflapMessages.epsilonLeftConcatenation(),
      RegexJflapMessages.epsilonRightConcatenation(),
      RegexJflapMessages.escapeMissingSymbol(),
      RegexJflapMessages.invalidSource(),
      RegexJsonMessages.unexpectedDecoderType(),
      RegexJsonMessages.sourceOfTruthInvalid(),
      RegexJsonMessages.canonicalAstMismatch(),
      RegexJsonMessages.expectedRegexDocument(),
      RegexJsonMessages.invalidDocument(),
      RegexJsonMessages.unsupportedDialect(),
      RegexJsonMessages.invalidSource(),
      RegexJsonMessages.unexpectedValidationOutcome(),
      PdaJflapMessages.invalidUtf8(),
      PdaJflapMessages.malformedXml(),
      PdaJflapMessages.invalidRoot(),
      PdaJflapMessages.unsupportedDocumentType('fa'),
      PdaJflapMessages.missingAutomaton(),
      PdaJflapMessages.missingStateId(),
      PdaJflapMessages.duplicateStateId('q0'),
      PdaJflapMessages.invalidStateCoordinate('q0'),
      PdaJflapMessages.invalidDocument(),
      PdaJflapMessages.unknownTransitionEndpoints(from: 'q0', to: 'q1'),
      PdaJflapMessages.invalidTransitionId(),
      PdaJflapMessages.duplicateTransitionId(),
      PdaJflapMessages.invalidAcceptanceMode(),
      PdaJflapMessages.malformedExtension(),
      PdaJflapMessages.canonicalOrderImport(),
      PdaJflapMessages.staleTokenExtension(),
      PdaJflapMessages.explicitEpsilonAliasInterpreted(),
      PdaJflapMessages.popWordTreatedAsAtomicToken(),
      PdaJflapMessages.acceptanceModeAssumedFinalState(),
      PdaJflapMessages.requiresPdaDocument(),
      PdaJflapMessages.unsupportedSchema(2),
      PdaJflapMessages.extensionPortability(),
      PdaJflapMessages.initialStackSymbolNotPortable(),
      PdaJflapMessages.acceptanceModeNotPortable(),
      PdaJflapMessages.atomicPopTokenNotPortable(),
      PdaJflapMessages.atomicPushTokenNotPortable(),
      PdaJflapMessages.unknownOptionalElement('vendor'),
      PdaJflapMessages.unknownOptionalAttribute('vendor'),
      PdaJflapMessages.invalidNotePosition(),
      PdaJflapMessages.notesNormalized(),
      PdaJflapMessages.notePresentationDropped(),
      PdaJflapMessages.unknownDiagnostic(),
      PdaJsonMessages.unexpectedDocumentType(),
      PdaJsonMessages.invalidDocument(),
      TmJflapMessages.invalidUtf8(),
      TmJflapMessages.malformedXml(),
      TmJflapMessages.invalidRoot(),
      TmJflapMessages.unsupportedDocumentType('fa'),
      TmJflapMessages.unsupportedFeature(),
      TmJflapMessages.invalidTapeCount(),
      TmJflapMessages.missingAutomaton(),
      TmJflapMessages.malformedExtension(),
      TmJflapMessages.canonicalOrderImport(),
      TmJflapMessages.canonicalOrderExport(),
      TmJflapMessages.variantMismatch(),
      TmJflapMessages.tapeCountMismatch(),
      TmJflapMessages.blankSymbolInvalid(),
      TmJflapMessages.acceptancePolicyInvalid(),
      TmJflapMessages.incompleteExtension(),
      TmJflapMessages.extensionSchemaInvalid(),
      TmJflapMessages.missingStateId(),
      TmJflapMessages.duplicateStateId('q0'),
      TmJflapMessages.invalidStateCoordinate('q0'),
      TmJflapMessages.invalidStateType('q0'),
      TmJflapMessages.invalidStateProperties('q0'),
      TmJflapMessages.invalidInitialStateCount(),
      TmJflapMessages.unknownTransitionEndpoints(from: 'q0', to: 'q1'),
      TmJflapMessages.invalidTapeIndex(),
      TmJflapMessages.duplicateTapeOperation('read'),
      TmJflapMessages.unsupportedReadPredicate(),
      TmJflapMessages.invalidReadSymbol(),
      TmJflapMessages.invalidWriteSymbol(),
      TmJflapMessages.invalidMove(),
      TmJflapMessages.invalidTransitionExtension(),
      TmJflapMessages.invalidTransitionId(),
      TmJflapMessages.duplicateTransitionId(),
      TmJflapMessages.invalidTransitionLabel('t0'),
      TmJflapMessages.invalidTransitionType('t0'),
      TmJflapMessages.invalidControlPoint(),
      TmJflapMessages.transitionIdentitiesReconstructed(),
      TmJflapMessages.invalidMetadata(),
      TmJflapMessages.invalidDocument(),
      TmJflapMessages.requiresTmDocument(),
      TmJflapMessages.unsupportedSchema(2),
      TmJflapMessages.unsupportedTapeCount(),
      TmJflapMessages.unsupportedOperation(
        transitionId: 't0',
        operation: 'read',
        symbol: 'a',
      ),
      TmJflapMessages.buildingBlockVariantMismatch(),
      TmJflapMessages.recursiveDependency('scan'),
      TmJflapMessages.missingBlockDefinition('scan'),
      TmJflapMessages.ambiguousBlockDefinition('scan'),
      TmJflapMessages.acceptancePolicyConflict(),
      TmJflapMessages.machineSchemaInvalid(),
      TmJflapMessages.machineVariantInvalid(),
      TmJflapMessages.machineTapeCountMismatch(),
      TmJflapMessages.machineBlankSymbolMismatch(),
      TmJflapMessages.missingBlockTag('scan'),
      TmJflapMessages.invalidNodeId(),
      TmJflapMessages.duplicateNodeId(),
      TmJflapMessages.invalidNodeCoordinate('node-1'),
      TmJflapMessages.invalidNodeStateType('node-1'),
      TmJflapMessages.invalidNodeProperties('node-1'),
      TmJflapMessages.missingBlockTagReference('scan'),
      TmJflapMessages.invalidOrDuplicateTapeIndex(),
      TmJflapMessages.transitionIdentityConflict(),
      TmJflapMessages.buildingBlocksImported(),
      TmJflapMessages.sharedTapes(),
      TmJflapMessages.unknownBuildingBlockExtensionDropped(),
      TmJflapMessages.buildingBlocksExported(),
      TmJflapMessages.extensionIdentities(),
      TmJflapMessages.extensionPortability(),
      TmJflapMessages.unknownOptionalElement('vendor'),
      TmJflapMessages.unknownOptionalAttribute('vendor'),
      TmJflapMessages.invalidNotePosition(),
      TmJflapMessages.notesNormalized(),
      TmJflapMessages.notePresentationDropped(),
      TmJflapMessages.unknownDiagnostic(),
      TmJsonMessages.unexpectedDocumentType(),
      TmJsonMessages.invalidDocument(),
      TmJsonMessages.variantMismatch(),
      TmJsonMessages.variantInferred(),
      TmJsonMessages.operationVectorsMigrated(),
      TmJsonMessages.endpointsMigratedToIds(),
      TmBuildingBlockMessages.enterBlock('block-1'),
      TmBuildingBlockMessages.transition('t1'),
      TmBuildingBlockMessages.returnFromBlock('block-1'),
      VersionedJsonMessages.invalidUtf8(),
      VersionedJsonMessages.rootMustBeObject(),
      VersionedJsonMessages.malformedJson(),
      VersionedJsonMessages.unsupportedDocument(),
      VersionedJsonMessages.legacyEnvelopeMigrated(),
      VersionedJsonMessages.unknownFieldPreserved(
        scope: 'payload',
        field: 'vendor',
      ),
      VersionedJsonMessages.envelopeVersionInvalid(),
      VersionedJsonMessages.unsupportedEnvelopeVersion(2),
      VersionedJsonMessages.missingDocument(),
      VersionedJsonMessages.documentKeyMismatch('fsa'),
      VersionedJsonMessages.missingSchema(),
      VersionedJsonMessages.schemaIdentityInvalid(),
      VersionedJsonMessages.unsupportedSchemaVersion(2),
      VersionedJsonMessages.missingPayload(),
      VersionedJsonMessages.sourceMetadataInvalid(),
      VersionedJsonMessages.sourceFieldInvalid('application'),
      VersionedJsonMessages.extensionsInvalid(),
      VersionedJsonMessages.migrationPathMissing(1),
      VersionedJsonMessages.migrationRejected(),
      VersionedJsonMessages.migrationInvalidValue(),
      VersionedJsonMessages.migrationFailed(),
      VersionedJsonMessages.schemaMigrated(fromVersion: 1, toVersion: 2),
      VersionedJsonMessages.extensionKeysInvalid(),
      VersionedJsonMessages.payloadValueTypeInvalid(),
      VersionedJsonMessages.decoderValueTypeInvalid(),
      VersionedJsonMessages.decoderFailed(),
      VersionedJsonMessages.encodeDocumentMismatch('fsa'),
      VersionedJsonMessages.encodeSchemaUnsupported(),
      VersionedJsonMessages.encodeValueInvalid(),
      VersionedJsonMessages.encoderFailed(),
      VersionedJsonMessages.sourceMetadataNormalized(),
      VersionedJsonMessages.unknownFieldsSidecarNormalized(),
      VersionedJsonMessages.envelopeSerializationFailed(),
    ];

    for (final message in messages) {
      final english = en.resolveStructuredMessage(message);
      final portuguese = pt.resolveStructuredMessage(message);
      expect(english, isNot(message.stableCode), reason: message.stableCode);
      expect(portuguese, isNot(message.stableCode), reason: message.stableCode);
    }
  });
}
