//
//  help_icon_mapper.dart
//  Turing Lab
//
//  Centralized icon mapping for help content identifiers to Material icons.
//
//  Thales Matheus Mendonça Santos - February 2026
//
import 'package:flutter/material.dart';

const Map<String, IconData> _helpIcons = {
  'abc': Icons.abc,
  'account_tree': Icons.account_tree,
  'add_circle_outline': Icons.add_circle_outline,
  'all_inclusive': Icons.all_inclusive,
  'analytics': Icons.analytics,
  'auto_awesome': Icons.auto_awesome,
  'auto_awesome_motion': Icons.auto_awesome_motion,
  'balance': Icons.balance,
  'build_circle': Icons.build_circle,
  'call_merge': Icons.call_merge,
  'call_split': Icons.call_split,
  'center_focus_strong': Icons.center_focus_strong,
  'check_circle': Icons.check_circle,
  'close': Icons.close,
  'code': Icons.code,
  'compare_arrows': Icons.compare_arrows,
  'compress': Icons.compress,
  'content_copy': Icons.content_copy,
  'dangerous': Icons.dangerous,
  'dashboard': Icons.dashboard,
  'data_object': Icons.data_object,
  'device_hub': Icons.device_hub,
  'devices': Icons.devices,
  'dynamic_form': Icons.dynamic_form,
  'east': Icons.east,
  'edit': Icons.edit,
  'edit_note': Icons.edit_note,
  'error_outline': Icons.error_outline,
  'explore': Icons.explore,
  'fact_check': Icons.fact_check,
  'filter_list': Icons.filter_list,
  'first_page': Icons.first_page,
  'fit_screen': Icons.fit_screen,
  'fitness_center': Icons.fitness_center,
  'flag': Icons.flag,
  'flip': Icons.flip,
  'folder_off': Icons.folder_off,
  'folder_open': Icons.folder_open,
  'format_list_bulleted': Icons.format_list_bulleted,
  'format_list_numbered': Icons.format_list_numbered,
  'functions': Icons.functions,
  'grid_on': Icons.grid_on,
  'groups': Icons.groups,
  'help_center': Icons.help_center,
  'help_outline': Icons.help_outline,
  'history': Icons.history,
  'hub': Icons.hub,
  'info_outline': Icons.info_outline,
  'input': Icons.input,
  'keyboard': Icons.keyboard,
  'keyboard_tab': Icons.keyboard_tab,
  'language': Icons.language,
  'last_page': Icons.last_page,
  'layers': Icons.layers,
  'looks_one': Icons.looks_one,
  'memory': Icons.memory,
  'merge_type': Icons.merge_type,
  'navigation': Icons.navigation,
  'near_me': Icons.near_me,
  'park': Icons.park,
  'park_outlined': Icons.park_outlined,
  'play_arrow': Icons.play_arrow,
  'play_circle': Icons.play_circle,
  'playlist_play': Icons.playlist_play,
  'policy': Icons.policy,
  'preview': Icons.preview,
  'query_stats': Icons.query_stats,
  'radio_button_checked': Icons.radio_button_checked,
  'refresh': Icons.refresh,
  'regular_expression': Icons.data_object,
  'remove_circle_outline': Icons.remove_circle_outline,
  'rocket_launch': Icons.rocket_launch,
  'route': Icons.route,
  'rule': Icons.rule,
  'schema': Icons.schema,
  'school': Icons.school,
  'school_outlined': Icons.school_outlined,
  'send': Icons.send,
  'signal_cellular_alt': Icons.signal_cellular_alt,
  'slow_motion_video': Icons.slow_motion_video,
  'space_dashboard': Icons.space_dashboard,
  'spellcheck': Icons.spellcheck,
  'sports_esports': Icons.sports_esports,
  'stacked_bar_chart': Icons.stacked_bar_chart,
  'storage': Icons.storage,
  'settings': Icons.settings,
  'swap_horiz': Icons.swap_horiz,
  'swap_calls': Icons.swap_calls,
  'sync_alt': Icons.sync_alt,
  'table_chart': Icons.table_chart,
  'table_view': Icons.table_view,
  'task_alt': Icons.task_alt,
  'text_fields': Icons.text_fields,
  'text_snippet': Icons.text_snippet,
  'timer': Icons.timer,
  'timer_off': Icons.timer_off,
  'transform': Icons.transform,
  'travel_explore': Icons.travel_explore,
  'trending_flat': Icons.trending_flat,
  'tune': Icons.tune,
  'verified': Icons.verified,
  'vertical_align_bottom': Icons.vertical_align_bottom,
  'vertical_align_center': Icons.vertical_align_center,
  'vertical_align_top': Icons.vertical_align_top,
  'view_agenda': Icons.view_agenda,
  'view_list': Icons.view_list,
  'view_sidebar': Icons.view_sidebar,
  'view_week': Icons.view_week,
  'volunteer_activism': Icons.volunteer_activism,
  'warning_amber': Icons.warning_amber,
  'zoom_in': Icons.zoom_in,
  'zoom_in_map': Icons.zoom_in_map,
};

IconData helpIconData(String iconName) {
  final normalizedName = iconName.trim().toLowerCase();
  final icon = _helpIcons[normalizedName];
  if (icon == null) {
    throw ArgumentError.value(iconName, 'iconName', 'Unknown Help icon name');
  }
  return icon;
}
