import 'dart:convert';
import 'dart:io';

import 'certification.dart';
import 'models.dart';
import 'report.dart';

final class HardEdgeCertificationReportWriter {
  const HardEdgeCertificationReportWriter();

  Future<void> write(
    HardEdgeCertificationReport report, {
    required Directory outputDirectory,
  }) async {
    await outputDirectory.create(recursive: true);
    if (report.propertyRun case final propertyRun?) {
      await const HardEdgeReportWriter().writeRun(
        propertyRun,
        outputDirectory: outputDirectory,
      );
    }
    if (report.mutationRun case final mutationRun?) {
      await const HardEdgeReportWriter().writeMutation(
        mutationRun,
        outputDirectory: outputDirectory,
      );
    }
    for (final evidence in report.inventoryEvidence) {
      final file = File(
        '${outputDirectory.path}${Platform.pathSeparator}'
        '${evidence.artifact.replaceAll('/', Platform.pathSeparator)}',
      );
      await file.parent.create(recursive: true);
      await file.writeAsString(
        'Command: ${evidence.command}\n'
        'Status: ${hardEdgeCertificationStatusName(evidence.status)}\n'
        'Exit code: ${evidence.exitCode ?? 'not_run'}\n'
        'Duration: ${evidence.duration.inMicroseconds}us\n\n'
        'STDOUT\n${evidence.stdout}\n\nSTDERR\n${evidence.stderr}\n',
        flush: true,
      );
    }
    await _writeJson(
      File(_path(outputDirectory, 'certification-report.json')),
      report.toJson(),
    );
    await File(_path(outputDirectory, 'certification-report.md'))
        .writeAsString(renderMarkdown(report), flush: true);
    await File(_path(outputDirectory, 'certification-report.html'))
        .writeAsString(renderHtml(report), flush: true);
  }

  String renderMarkdown(HardEdgeCertificationReport report) {
    final buffer = StringBuffer()
      ..writeln('<!-- Generated by tool/hard_edge_cases.dart certify. -->')
      ..writeln('# Local algorithm certification')
      ..writeln()
      ..writeln(
        '- Status: `${hardEdgeCertificationStatusName(report.status)}`',
      )
      ..writeln('- Remotely verified: `false`')
      ..writeln('- Revision: `${report.environment.revision ?? 'not_run'}`')
      ..writeln('- Dirty worktree: `${report.environment.dirty ?? 'not_run'}`')
      ..writeln('- OS: `${_cell(report.environment.operatingSystem)}`')
      ..writeln('- Duration: `${_duration(report.duration)}`')
      ..writeln('- Command: `${_cell(report.command)}`')
      ..writeln()
      ..writeln('## Toolchains and prerequisites')
      ..writeln()
      ..writeln('| Tool | Status | Version | Command | Message |')
      ..writeln('| --- | --- | --- | --- | --- |');
    final tools = <HardEdgeToolchainRecord>[
      ...report.environment.toolchains,
      ...report.prerequisites.where(
        (required) => !report.environment.toolchains.any(
          (recorded) => recorded.name == required.name,
        ),
      ),
    ];
    for (final tool in tools) {
      buffer.writeln(
        '| `${_cell(tool.name)}` '
        '| `${hardEdgeCertificationStatusName(tool.status)}` '
        '| `${_cell(tool.version ?? 'not_run')}` '
        '| `${_cell(tool.command)}` '
        '| ${_cell(tool.message)} |',
      );
    }
    buffer
      ..writeln()
      ..writeln('## Phases')
      ..writeln()
      ..writeln('| Phase | Status | Duration | Reason |')
      ..writeln('| --- | --- | ---: | --- |');
    for (final phase in report.phases) {
      buffer.writeln(
        '| `${_cell(phase.name)}` '
        '| `${hardEdgeCertificationStatusName(phase.status)}` '
        '| `${_duration(phase.duration)}` '
        '| ${_cell(phase.reason)} |',
      );
    }
    _writeMutationMarkdown(buffer, report);
    _writeCrossFamilyMarkdown(buffer, report);
    _writeJflapMarkdown(buffer, report);
    _writeInventoryMarkdown(buffer, report);
    _writeInventoryEvidenceMarkdown(buffer, report);
    _writeRegressionMarkdown(buffer, report);
    _writeSeedMarkdown(buffer, report);
    _writeFlakinessMarkdown(buffer, report);
    _writeQuarantineMarkdown(buffer, report);
    buffer
      ..writeln('## Artifacts')
      ..writeln();
    for (final artifact in report.artifacts) {
      buffer.writeln('- `${_cell(artifact)}`');
    }
    buffer
      ..writeln()
      ..writeln(
        'This report is local only. A failed prerequisite, bounded or '
        'inapplicable result, missing execution, explicit skip, survivor, '
        'flaky repeat, or quarantine is never converted into a pass.',
      );
    return buffer.toString();
  }

  String renderHtml(HardEdgeCertificationReport report) {
    final buffer = StringBuffer()
      ..writeln('<!doctype html>')
      ..writeln('<html lang="en"><head><meta charset="utf-8">')
      ..writeln('<meta name="viewport" content="width=device-width">')
      ..writeln('<title>Local algorithm certification</title>')
      ..writeln('<style>')
      ..writeln('body{font:16px/1.5 system-ui,sans-serif;max-width:1200px;'
          'margin:2rem auto;padding:0 1rem;color:#171717}')
      ..writeln('table{border-collapse:collapse;width:100%;margin:1rem 0}')
      ..writeln('th,td{border:1px solid #bbb;padding:.4rem;text-align:left;'
          'vertical-align:top}code{overflow-wrap:anywhere}')
      ..writeln('</style></head><body>')
      ..writeln('<h1>Local algorithm certification</h1>')
      ..writeln('<dl>')
      ..writeln('<dt>Status</dt><dd><code>${_html(
        hardEdgeCertificationStatusName(report.status),
      )}</code></dd>')
      ..writeln('<dt>Remotely verified</dt><dd><code>false</code></dd>')
      ..writeln('<dt>Revision</dt><dd><code>${_html(
        report.environment.revision ?? 'not_run',
      )}</code></dd>')
      ..writeln('<dt>OS</dt><dd>${_html(report.environment.operatingSystem)} '
          '${_html(report.environment.operatingSystemVersion)}</dd>')
      ..writeln(
          '<dt>Duration</dt><dd>${_html(_duration(report.duration))}</dd>')
      ..writeln(
          '<dt>Command</dt><dd><code>${_html(report.command)}</code></dd>')
      ..writeln('</dl>')
      ..writeln('<h2>Phases</h2>')
      ..writeln('<table><thead><tr><th>Phase</th><th>Status</th>'
          '<th>Duration</th><th>Reason</th></tr></thead><tbody>');
    for (final phase in report.phases) {
      buffer.writeln('<tr><td><code>${_html(phase.name)}</code></td>'
          '<td><code>${_html(hardEdgeCertificationStatusName(phase.status))}'
          '</code></td><td>${_html(_duration(phase.duration))}</td>'
          '<td>${_html(phase.reason)}</td></tr>');
    }
    buffer
      ..writeln('</tbody></table>')
      ..writeln('<h2>Cross-family outcomes</h2>')
      ..writeln(
          '<p>${report.crossFamily == null ? 'skipped' : report.crossFamily!.expectedOutcomesMatched && !report.crossFamily!.flaky ? 'passed' : 'failed'}; '
          '${report.crossFamily?.report.inconclusiveCount ?? 0} expected '
          'boundedUnknown observations.</p>')
      ..writeln('<h2>JFLAP parity</h2>')
      ..writeln('<p>${report.jflapParity.totalRows} rows; '
          '${report.jflapParity.residualGaps.length} residual gaps.</p>')
      ..writeln('<h2>Repository inventory</h2>')
      ..writeln('<p>${report.repositoryInventory.entries} owned entries; '
          '${report.repositoryInventory.exclusions} reviewed support '
          'exclusions; ${report.repositoryInventory.mutationExclusions.length} '
          'reviewed mutation exclusions.</p>')
      ..writeln('<h2>Mutation thresholds</h2>')
      ..writeln('<table><thead><tr><th>Family</th><th>Killed</th>'
          '<th>Survived</th><th>Not run</th><th>Kill ratio</th>'
          '<th>Threshold met</th></tr></thead><tbody>');
    for (final family in report.mutationFamilies) {
      buffer.writeln('<tr><td><code>${_html(family.family)}</code></td>'
          '<td>${family.killed}</td><td>${family.survived}</td>'
          '<td>${family.notRun}</td><td>${_html(_ratio(family.killRatio))}</td>'
          '<td>${family.thresholdMet}</td></tr>');
    }
    if (report.mutationFamilies.isEmpty) {
      buffer.writeln('<tr><td colspan="6"><code>not_run</code></td></tr>');
    }
    buffer
      ..writeln('</tbody></table>')
      ..writeln('<h2>Regression fixture index</h2>')
      ..writeln('<p>${report.regressionIndex.length} committed historical '
          'regression fixtures.</p>')
      ..writeln('<h2>Seed catalog</h2>')
      ..writeln('<p>${report.seedCatalog.length} selected catalog entries.</p>')
      ..writeln('<h2>Flakiness</h2>')
      ..writeln(
          '<p>${report.propertyRun?.flakyCaseIds.isEmpty == false ? 'failed' : report.propertyRun == null ? 'not_run' : 'passed'}</p>')
      ..writeln('<ul>');
    for (final id in report.propertyRun?.flakyCaseIds ?? const <String>[]) {
      buffer.writeln('<li><code>${_html(id)}</code></li>');
    }
    buffer
      ..writeln('</ul><h2>Quarantines</h2>')
      ..writeln(
          '<p>${report.quarantines.isEmpty ? 'None.' : '${report.quarantines.length} explicitly skipped.'}</p>')
      ..writeln('<p>This report is local only. Missing, skipped, failed and '
          'passed states remain distinct.</p>')
      ..writeln('</body></html>');
    return buffer.toString();
  }

  void _writeMutationMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    buffer
      ..writeln()
      ..writeln('## Mutation thresholds and survivors')
      ..writeln()
      ..writeln(
        '| Family | Killed | Survived | Not run | Kill ratio | '
        'Minimum | Maximum survivors | Met |',
      )
      ..writeln('| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |');
    for (final family in report.mutationFamilies) {
      buffer.writeln(
        '| `${_cell(family.family)}` | ${family.killed} | ${family.survived} '
        '| ${family.notRun} | `${_ratio(family.killRatio)}` '
        '| `${_ratio(family.threshold.minimumKillRatio)}` '
        '| ${family.threshold.maximumSurvivors} '
        '| `${family.thresholdMet}` |',
      );
      for (final survivor in family.survivorIds) {
        buffer.writeln('  - Survivor: `${_cell(survivor)}`');
      }
    }
    if (report.mutationFamilies.isEmpty) {
      buffer.writeln('| `not_run` | 0 | 0 | 0 | `not_run` | — | — | `false` |');
    }
  }

  void _writeCrossFamilyMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    final summary = report.crossFamily;
    buffer
      ..writeln()
      ..writeln('## Cross-family certification')
      ..writeln();
    if (summary == null) {
      buffer.writeln('- Status: `skipped` or `not_run`; see the phase table.');
      return;
    }
    buffer
      ..writeln(
        '- Status: `${summary.expectedOutcomesMatched && !summary.flaky ? 'passed' : 'failed'}`',
      )
      ..writeln(
        '- Seeds: `${summary.seeds.isEmpty ? [summary.seed] : summary.seeds}`',
      )
      ..writeln('- Repeats: `${summary.repeats}`')
      ..writeln('- Flaky: `${summary.flaky}`')
      ..writeln('- Flaky seeds: `${summary.flakySeeds}`')
      ..writeln('- Verified outcomes: `${summary.report.certificationCount}`')
      ..writeln(
        '- Expected boundedUnknown outcomes: '
        '`${summary.report.inconclusiveCount}`',
      )
      ..writeln()
      ..writeln('| Check | Equivalence | Expected | Actual | Certified |')
      ..writeln('| --- | --- | --- | --- | --- |');
    for (final observation in summary.report.observations) {
      buffer.writeln('| `${_cell(observation.id)}` '
          '| `${observation.equivalence.name}` '
          '| `${summary.expectedOutcomes[observation.id]?.name ?? 'missing'}` '
          '| `${observation.outcome.name}` '
          '| `${observation.certified}` |');
    }
    buffer.writeln(
      'Expected boundedUnknown rows satisfy their declared bounded contract, '
      'but remain `certified=false` and are not universal proofs.',
    );
  }

  void _writeJflapMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    final parity = report.jflapParity;
    buffer
      ..writeln()
      ..writeln('## JFLAP parity summary')
      ..writeln()
      ..writeln(
          '- Status: `${parity.residualGaps.isEmpty ? 'passed' : 'failed'}`')
      ..writeln('- Rows: `${parity.totalRows}`')
      ..writeln()
      ..writeln('| Status | Rows |')
      ..writeln('| --- | ---: |');
    for (final status in parity.statusCounts.keys.toList()..sort()) {
      buffer.writeln('| `${_cell(status)}` | ${parity.statusCounts[status]} |');
    }
    if (parity.residualGaps.isNotEmpty) {
      buffer
        ..writeln()
        ..writeln('| Residual row | Status | Owner issues | Unowned |')
        ..writeln('| --- | --- | --- | --- |');
      for (final gap in parity.residualGaps) {
        buffer.writeln('| `${_cell('${gap['id']}')}` '
            '| `${_cell('${gap['status']}')}` '
            '| `${_cell('${gap['ownerIssues']}')}` '
            '| `${gap['unowned']}` |');
      }
    }
  }

  void _writeInventoryMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    final inventory = report.repositoryInventory;
    final repositoryDefects =
        report.repositoryRegressionIndex['historicalDefects'] as List;
    buffer
      ..writeln()
      ..writeln('## Repository inventory and regression index')
      ..writeln()
      ..writeln(
        '- Inventory status: '
        '`${inventory.validationIssues.isEmpty ? 'passed' : 'failed'}`',
      )
      ..writeln('- Inventory path: `${_cell(inventory.path)}`')
      ..writeln('- Owned entries: `${inventory.entries}`')
      ..writeln('- Reviewed support exclusions: `${inventory.exclusions}`')
      ..writeln(
        '- Repository regression index: '
        '`${_cell('${report.repositoryRegressionIndex['path'] ?? 'embedded'}')}`',
      )
      ..writeln(
          '- Repository historical defects: `${repositoryDefects.length}`');
    for (final issue in inventory.validationIssues) {
      buffer.writeln('- Inventory error: ${_cell(issue)}');
    }
    buffer
      ..writeln()
      ..writeln('### Reviewed mutation exclusions')
      ..writeln();
    if (inventory.mutationExclusions.isEmpty) {
      buffer.writeln('No inventory entry excludes a standalone mutation.');
    } else {
      buffer
        ..writeln('| Entry | Family | Decision | Rationale |')
        ..writeln('| --- | --- | --- | --- |');
      for (final exclusion in inventory.mutationExclusions) {
        buffer.writeln('| `${_cell('${exclusion['id']}')}` '
            '| `${_cell('${exclusion['family']}')}` '
            '| `${_cell('${exclusion['status']}')}` '
            '| ${_cell('${exclusion['rationale']}')} |');
      }
    }
  }

  void _writeInventoryEvidenceMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    buffer
      ..writeln()
      ..writeln('## Inventory owner evidence')
      ..writeln()
      ..writeln('| Command | Status | Exit | Duration | Artifact |')
      ..writeln('| --- | --- | ---: | ---: | --- |');
    for (final evidence in report.inventoryEvidence) {
      buffer.writeln('| `${_cell(evidence.command)}` '
          '| `${hardEdgeCertificationStatusName(evidence.status)}` '
          '| `${evidence.exitCode ?? 'not_run'}` '
          '| `${_duration(evidence.duration)}` '
          '| `${_cell(evidence.artifact)}` |');
    }
    if (report.inventoryEvidence.isEmpty) {
      buffer.writeln('| — | `not_run` | — | — | — |');
    }
  }

  void _writeRegressionMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    buffer
      ..writeln()
      ..writeln('## Regression fixture index')
      ..writeln()
      ..writeln('| Case | Family | Property | Issue | Seed | Fixture |')
      ..writeln('| --- | --- | --- | ---: | ---: | --- |');
    for (final item in report.regressionIndex) {
      buffer.writeln('| `${_cell('${item['id']}')}` '
          '| `${_cell('${item['family']}')}` '
          '| `${_cell('${item['property']}')}` '
          '| ${item['issue']} | ${item['seed']} '
          '| `${_cell('${item['fixture']}')}` |');
    }
    if (report.regressionIndex.isEmpty) {
      buffer.writeln('| `not_run` | — | — | — | — | No historical fixture. |');
    }
  }

  void _writeSeedMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    buffer
      ..writeln()
      ..writeln('## Seed catalog')
      ..writeln()
      ..writeln('| Case | Family | Property | Seed | Source kind |')
      ..writeln('| --- | --- | --- | ---: | --- |');
    for (final item in report.seedCatalog) {
      buffer.writeln('| `${_cell('${item['id']}')}` '
          '| `${_cell('${item['family']}')}` '
          '| `${_cell('${item['property']}')}` '
          '| ${item['seed']} | `${_cell('${item['sourceKind']}')}` |');
    }
    if (report.seedCatalog.isEmpty) {
      buffer.writeln('| `not_run` | — | — | — | — |');
    }
  }

  void _writeFlakinessMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    final flaky = report.propertyRun?.flakyCaseIds;
    buffer
      ..writeln()
      ..writeln('## Flakiness')
      ..writeln()
      ..writeln(
          '- Status: `${flaky == null ? 'not_run' : flaky.isEmpty ? 'passed' : 'failed'}`')
      ..writeln('- Repeat count is preserved in every property case record.');
    for (final id in flaky ?? const <String>[]) {
      buffer.writeln('- Flaky case: `${_cell(id)}`');
    }
  }

  void _writeQuarantineMarkdown(
    StringBuffer buffer,
    HardEdgeCertificationReport report,
  ) {
    buffer
      ..writeln()
      ..writeln('## Quarantines')
      ..writeln();
    if (report.quarantines.isEmpty) {
      buffer.writeln('No check is quarantined.');
      return;
    }
    buffer
      ..writeln(
          '| Check | Status | Issue | Owner | Reason | Review condition |')
      ..writeln('| --- | --- | ---: | --- | --- | --- |');
    for (final item in report.quarantines) {
      buffer.writeln('| `${_cell(item.checkId)}` | `skipped` | ${item.issue} '
          '| `${_cell(item.owner)}` | ${_cell(item.reason)} '
          '| ${_cell(item.reviewCondition)} |');
    }
  }
}

Future<void> _writeJson(File file, Object? value) => file.writeAsString(
      '${const JsonEncoder.withIndent('  ').convert(
        jsonDecode(canonicalJsonEncode(value)),
      )}\n',
      flush: true,
    );

String _path(Directory directory, String name) =>
    '${directory.path}${Platform.pathSeparator}$name';

String _duration(Duration value) => '${value.inMilliseconds}ms';

String _ratio(double? value) =>
    value == null ? 'not_run' : value.toStringAsFixed(4);

String _cell(String value) =>
    value.replaceAll('|', r'\|').replaceAll('\n', ' ');

String _html(String value) => value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
