import 'dart:convert';
import 'dart:io';

import 'catalog.dart';
import 'models.dart';
import 'runner.dart';

final class HardEdgeReportWriter {
  const HardEdgeReportWriter();

  Future<void> writeRun(
    HardEdgeRunResult result, {
    required Directory outputDirectory,
    HardEdgeCatalog? catalog,
  }) async {
    await outputDirectory.create(recursive: true);
    final jsonFile = File(
      '${outputDirectory.path}${Platform.pathSeparator}hard-edge-report.json',
    );
    final markdownFile = File(
      '${outputDirectory.path}${Platform.pathSeparator}hard-edge-report.md',
    );
    await _writeJson(jsonFile, result.toJson());
    await markdownFile.writeAsString(
      renderRunMarkdown(result, outputDirectory: outputDirectory),
      flush: true,
    );
    await _writeFailureArtifacts(result, outputDirectory);
  }

  Future<void> writeMutation(
    HardEdgeMutationRunResult result, {
    required Directory outputDirectory,
  }) async {
    await outputDirectory.create(recursive: true);
    await _writeJson(
      File(
        '${outputDirectory.path}${Platform.pathSeparator}'
        'mutation-report.json',
      ),
      result.toJson(),
    );
    await File(
      '${outputDirectory.path}${Platform.pathSeparator}mutation-report.md',
    ).writeAsString(renderMutationMarkdown(result), flush: true);
  }

  String renderRunMarkdown(
    HardEdgeRunResult result, {
    Directory? outputDirectory,
  }) {
    final artifactDirectory = outputDirectory ?? Directory('build/hard-edge');
    final artifactCases = result.cases
        .where((resultCase) => _needsFailureArtifact(result, resultCase))
        .toList();
    final regenerationCases = result.cases
        .where((resultCase) => _needsRegeneration(result, resultCase))
        .toList();
    final buffer = StringBuffer()
      ..writeln('<!-- Generated by tool/hard_edge_cases.dart. -->')
      ..writeln('# Hard-edge property report')
      ..writeln()
      ..writeln('- Catalog version: `${result.catalogVersion}`')
      ..writeln('- Local result: `${result.status.name}`')
      ..writeln('- Remotely verified: `false`')
      ..writeln('- Jobs requested: `${result.jobs}`')
      ..writeln('- Per-case timeout: `${result.caseTimeout.inSeconds}s`')
      ..writeln('- Flaky cases: `${result.flakyCaseIds.length}`')
      ..writeln()
      ..writeln(
          '| Case | Family | Algorithm | Property | Seed | Result | Outcome |')
      ..writeln('| --- | --- | --- | --- | ---: | --- | --- |');
    for (final resultCase in result.cases) {
      buffer.writeln(
        '| `${_cell(resultCase.testCase.id)}` '
        '| `${_cell(resultCase.testCase.family)}` '
        '| `${_cell(resultCase.testCase.algorithm)}` '
        '| `${_cell(resultCase.testCase.property)}` '
        '| ${resultCase.testCase.seed} '
        '| `${resultCase.status.name}` '
        '| `${resultCase.outcome?.name ?? 'runnerError'}` |',
      );
    }
    buffer
      ..writeln()
      ..writeln('## Replay commands')
      ..writeln();
    if (artifactCases.isEmpty) {
      buffer.writeln('No replayable materialized failure was recorded.');
    } else {
      for (final resultCase in artifactCases) {
        final artifact = hardEdgeFailureArtifactFile(
          outputDirectory: artifactDirectory,
          resultCase: resultCase,
        );
        buffer
          ..writeln(
            '`${_cell(resultCase.testCase.id)}` repeat '
            '`${resultCase.repeatIndex}`',
          )
          ..writeln()
          ..writeln('```bash')
          ..writeln(
            'dart run tool/hard_edge_cases.dart replay --fixture '
            '${artifact.path}',
          )
          ..writeln('```')
          ..writeln();
      }
    }
    buffer
      ..writeln()
      ..writeln('## Regeneration commands')
      ..writeln();
    if (regenerationCases.isEmpty) {
      buffer.writeln('No failing, incomplete, or flaky case was recorded.');
    } else {
      for (final resultCase in regenerationCases) {
        buffer
          ..writeln(
            '`${_cell(resultCase.testCase.id)}` repeat '
            '`${resultCase.repeatIndex}`',
          )
          ..writeln()
          ..writeln('```bash')
          ..writeln(resultCase.reproductionCommand)
          ..writeln('```')
          ..writeln();
      }
    }
    buffer.writeln(
      'Results are local only. Missing, bounded, or inapplicable evidence is '
      'never reported as a pass.',
    );
    return buffer.toString();
  }

  String renderMutationMarkdown(HardEdgeMutationRunResult result) {
    final buffer = StringBuffer()
      ..writeln('<!-- Generated by tool/hard_edge_cases.dart. -->')
      ..writeln('# Hard-edge mutation report')
      ..writeln()
      ..writeln('- Local result: `${result.status.name}`')
      ..writeln('- Remotely verified: `false`')
      ..writeln()
      ..writeln('| Mutant | Family | Property | Operator | Result |')
      ..writeln('| --- | --- | --- | --- | --- |');
    for (final mutation in result.mutations) {
      buffer.writeln(
        '| `${_cell(mutation.mutation.id)}` '
        '| `${_cell(mutation.mutation.family)}` '
        '| `${_cell(mutation.mutation.property)}` '
        '| `${_cell(mutation.mutation.operatorId)}` '
        '| `${mutation.status.name}` |',
      );
    }
    if (result.mutations.isEmpty) {
      buffer.writeln('| — | — | — | — | `notRun` |');
    }
    buffer
      ..writeln()
      ..writeln(
          'A surviving mutant fails the command. Results are local only.');
    return buffer.toString();
  }

  Future<void> renderSummaryFromJson({
    required File reportFile,
    required File outputFile,
  }) async {
    final decoded = jsonDecode(await reportFile.readAsString());
    if (decoded is! Map || decoded['remotelyVerified'] != false) {
      throw const FormatException(
        'Summary input must be a hard-edge JSON report with '
        'remotelyVerified=false.',
      );
    }
    final status = decoded['status'];
    final cases = decoded['cases'];
    final mutations = decoded['mutations'];
    if (status is! String || (cases is! List && mutations is! List)) {
      throw const FormatException('Summary input has an invalid schema.');
    }
    final rows = cases is List ? cases : mutations as List;
    final buffer = StringBuffer()
      ..writeln('<!-- Generated by tool/hard_edge_cases.dart summary. -->')
      ..writeln('# Hard-edge local summary')
      ..writeln()
      ..writeln('- Local result: `$status`')
      ..writeln('- Remotely verified: `false`');
    if (cases is List) {
      final coverage = _readCoverage(decoded['coverage']);
      buffer
        ..writeln(
          '- Recorded unique cases: `${_coverageTotal(coverage.families)}`',
        )
        ..writeln('- Recorded executions: `${rows.length}`')
        ..writeln();
      _writeCoverageTable(buffer, 'family', coverage.families);
      _writeCoverageTable(buffer, 'property', coverage.properties);
      _writeCoverageTable(buffer, 'seed', coverage.seeds);
    } else {
      buffer
        ..writeln('- Recorded mutations: `${rows.length}`')
        ..writeln();
    }
    await outputFile.parent.create(recursive: true);
    await outputFile.writeAsString(buffer.toString(), flush: true);
  }

  Future<void> _writeFailureArtifacts(
    HardEdgeRunResult result,
    Directory outputDirectory,
  ) async {
    for (final resultCase in result.cases) {
      if (!_needsFailureArtifact(result, resultCase)) continue;
      final artifact = HardEdgeFailureArtifact(
        testCase: resultCase.testCase.copyWith(
          sha256: resultCase.fixtureFingerprint,
        ),
        fixture: resultCase.fixture,
        minimalFixture: null,
        minimized: false,
      );
      final file = hardEdgeFailureArtifactFile(
        outputDirectory: outputDirectory,
        resultCase: resultCase,
      );
      await file.parent.create(recursive: true);
      await _writeJson(file, artifact.toJson());
    }
  }
}

File hardEdgeFailureArtifactFile({
  required Directory outputDirectory,
  required HardEdgeCaseResult resultCase,
}) {
  final family = _safeSegment(resultCase.testCase.family);
  final property = _safeSegment(resultCase.testCase.property);
  final id = _safeSegment(resultCase.testCase.id);
  final repeat = resultCase.repeatIndex;
  return File(
    '${outputDirectory.path}${Platform.pathSeparator}failures'
    '${Platform.pathSeparator}$family${Platform.pathSeparator}$property'
    '${Platform.pathSeparator}$id-repeat-$repeat.json',
  );
}

bool _needsFailureArtifact(
  HardEdgeRunResult result,
  HardEdgeCaseResult resultCase,
) =>
    resultCase.fixtureMaterialized && _needsRegeneration(result, resultCase);

bool _needsRegeneration(
  HardEdgeRunResult result,
  HardEdgeCaseResult resultCase,
) =>
    resultCase.status != HardEdgeCaseStatus.passed ||
    result.flakyCaseIds.contains(resultCase.testCase.id);

typedef _Coverage = ({
  Map<String, int> families,
  Map<String, int> properties,
  Map<String, int> seeds,
});

_Coverage _readCoverage(Object? value) {
  if (value is! Map) {
    throw const FormatException('Run summary input has no coverage data.');
  }
  final coverage = <String, Object?>{
    for (final entry in value.entries) entry.key.toString(): entry.value,
  };
  return (
    families: _readCoverageCounts(coverage['families'], 'families'),
    properties: _readCoverageCounts(coverage['properties'], 'properties'),
    seeds: _readCoverageCounts(coverage['seeds'], 'seeds'),
  );
}

Map<String, int> _readCoverageCounts(Object? value, String dimension) {
  if (value is! Map) {
    throw FormatException('Run summary coverage has invalid $dimension.');
  }
  final counts = <String, int>{};
  for (final entry in value.entries) {
    final count = entry.value;
    if (count is! int || count < 0) {
      throw FormatException('Run summary coverage has invalid $dimension.');
    }
    counts[entry.key.toString()] = count;
  }
  return counts;
}

int _coverageTotal(Map<String, int> counts) =>
    counts.values.fold(0, (total, count) => total + count);

void _writeCoverageTable(
  StringBuffer buffer,
  String dimension,
  Map<String, int> counts,
) {
  final label = '${dimension[0].toUpperCase()}${dimension.substring(1)}';
  buffer
    ..writeln('## Coverage by $dimension')
    ..writeln()
    ..writeln('| $label | Unique cases |')
    ..writeln('| --- | ---: |');
  for (final entry in counts.entries) {
    buffer.writeln('| `${_cell(entry.key)}` | ${entry.value} |');
  }
  if (counts.isEmpty) {
    buffer.writeln('| — | 0 |');
  }
  buffer.writeln();
}

Future<void> _writeJson(File file, Object? value) => file.writeAsString(
      '${const JsonEncoder.withIndent('  ').convert(
        jsonDecode(canonicalJsonEncode(value)),
      )}\n',
      flush: true,
    );

String _safeSegment(String value) {
  if (!RegExp(r'^[a-z0-9][a-z0-9._-]*$').hasMatch(value)) {
    throw FormatException('Unsafe report path segment: $value');
  }
  return value;
}

String _cell(String value) =>
    value.replaceAll('|', r'\|').replaceAll('\n', ' ');
