import 'dart:convert';
import 'dart:io';

import 'runner.dart';

final class CompatibilityReportWriter {
  const CompatibilityReportWriter();

  Future<void> write(
    CompatibilityRunResult result, {
    required Directory outputDirectory,
    File? publicMatrix,
  }) async {
    await outputDirectory.create(recursive: true);
    final jsonFile = File(
      '${outputDirectory.path}${Platform.pathSeparator}'
      'compatibility-report.json',
    );
    final markdownFile = File(
      '${outputDirectory.path}${Platform.pathSeparator}'
      'compatibility-report.md',
    );
    await jsonFile.writeAsString(
      '${const JsonEncoder.withIndent('  ').convert(result.toJson())}\n',
    );
    final markdown = renderMarkdown(result);
    await markdownFile.writeAsString(markdown);
    if (publicMatrix != null) {
      await publicMatrix.parent.create(recursive: true);
      await publicMatrix.writeAsString(markdown);
    }
  }

  String renderMarkdown(CompatibilityRunResult result) {
    final buffer = StringBuffer()
      ..writeln('<!-- Generated by tool/compatibility_corpus.dart. -->')
      ..writeln('# JFLAP compatibility matrix')
      ..writeln()
      ..writeln('- Corpus version: `${result.corpusVersion}`')
      ..writeln('- Local result: `${result.status.name}`')
      ..writeln('- Remotely verified: `false`')
      ..writeln()
      ..writeln(
        'A successful parse is not treated as exact fidelity. Structural, '
        'semantic, visual, and metadata expectations come from the versioned '
        'corpus manifest.',
      )
      ..writeln()
      ..writeln(
        '| Fixture | Family | Codec | Equivalent | Result | Fidelity | Dimensions |',
      )
      ..writeln('| --- | --- | --- | --- | --- | --- | --- |');
    for (final resultCase in result.cases) {
      final dimensions = resultCase.testCase.expectation.dimensions.entries
          .map((entry) => '${entry.key}:${entry.value.name}')
          .join(', ');
      buffer.writeln(
        '| `${_cell(resultCase.testCase.id)}` '
        '| ${_cell(resultCase.testCase.family)} '
        '| `${_cell(resultCase.testCase.codecId)}` '
        '| `${_cell(resultCase.testCase.equivalent?.codecId ?? 'n/a')}` '
        '| `${resultCase.status.name}` '
        '| `${resultCase.actualFidelity ?? 'n/a'}` '
        '| ${_cell(dimensions)} |',
      );
    }
    buffer
      ..writeln()
      ..writeln('## Known unsupported capabilities')
      ..writeln()
      ..writeln('| Codec | Capability |')
      ..writeln('| --- | --- |');
    final capabilities = <String, Set<String>>{};
    for (final resultCase in result.cases) {
      capabilities
          .putIfAbsent(resultCase.testCase.codecId, () => <String>{})
          .addAll(resultCase.testCase.expectation.unsupportedCapabilities);
    }
    var wroteCapability = false;
    for (final codecId in capabilities.keys.toList()..sort()) {
      for (final capability in capabilities[codecId]!.toList()..sort()) {
        wroteCapability = true;
        buffer.writeln('| `${_cell(codecId)}` | ${_cell(capability)} |');
      }
    }
    if (!wroteCapability) buffer.writeln('| — | None declared |');
    buffer
      ..writeln()
      ..writeln('## Local command')
      ..writeln()
      ..writeln('```bash')
      ..writeln('dart run tool/compatibility_corpus.dart')
      ..writeln('```')
      ..writeln()
      ..writeln(
        'The command writes JSON and Markdown reports under '
        '`build/compatibility/`. Use `--update-public` to regenerate this '
        'tracked matrix. Results are local only.',
      );
    return buffer.toString();
  }
}

String _cell(String value) =>
    value.replaceAll('|', r'\|').replaceAll('\n', ' ');
